CREATE OR REFRESH MATERIALIZED VIEW ${table_name} (
  `AvailabilityZone` STRING COMMENT 'Provider-assigned availability zone where the usage ran.',
  `BilledCost` DOUBLE COMMENT 'Invoice cost after reduced rates and discounts, excluding amortized upfront charges.',
  `BillingAccountId` STRING COMMENT 'Provider-assigned identifier for the billing account.',
  `BillingAccountName` STRING COMMENT 'Display name for the billing account.',
  `BillingAccountType` STRING COMMENT 'Provider-assigned billing account type.',
  `BillingCurrency` STRING COMMENT 'Currency used for the billed charge.',
  `BillingPeriodEnd` TIMESTAMP COMMENT 'Exclusive end timestamp of the billing period.',
  `BillingPeriodStart` TIMESTAMP COMMENT 'Inclusive start timestamp of the billing period.',
  `CapacityReservationId` STRING COMMENT 'Provider-assigned capacity reservation identifier.',
  `CapacityReservationStatus` STRING COMMENT 'Whether the charge is used or unused capacity reservation commitment.',
  `ChargeCategory` STRING COMMENT 'Top-level billing classification for the charge.',
  `ChargeClass` STRING COMMENT 'Indicates whether the row corrects a previously invoiced period.',
  `ChargeDescription` STRING COMMENT 'Summary of what the charge is for and how it was priced.',
  `ChargeFrequency` STRING COMMENT 'How often the charge occurs.',
  `ChargePeriodEnd` TIMESTAMP COMMENT 'Exclusive end timestamp for the charge period.',
  `ChargePeriodStart` TIMESTAMP COMMENT 'Inclusive start timestamp for the charge period.',
  `CommitmentDiscountCategory` STRING COMMENT 'Whether the commitment discount is usage-based or spend-based.',
  `CommitmentDiscountId` STRING COMMENT 'Provider-assigned commitment discount identifier.',
  `CommitmentDiscountName` STRING COMMENT 'Display name for the commitment discount.',
  `CommitmentDiscountQuantity` DOUBLE COMMENT 'Purchased or allocated commitment discount amount in commitment units.',
  `CommitmentDiscountStatus` STRING COMMENT 'Whether the row represents used or unused commitment discount.',
  `CommitmentDiscountType` STRING COMMENT 'Provider-assigned type of commitment discount.',
  `CommitmentDiscountUnit` STRING COMMENT 'Measurement unit for the commitment discount quantity.',
  `ConsumedQuantity` DOUBLE COMMENT 'Measured usage volume for the resource or service.',
  `ConsumedUnit` STRING COMMENT 'Provider unit used to measure consumed usage.',
  `ContractedCost` DOUBLE COMMENT 'Cost calculated from contracted unit price and pricing quantity.',
  `ContractedUnitPrice` DOUBLE COMMENT 'Negotiated unit price before commitment discounts or other discounts.',
  `EffectiveCost` DOUBLE COMMENT 'Amortized cost after rates, discounts, and applicable prepaid purchases.',
  `InvoiceId` STRING COMMENT 'Provider-assigned invoice identifier for the billing period.',
  `InvoiceIssuerName` STRING COMMENT 'Entity responsible for issuing the invoice.',
  `ListCost` DOUBLE COMMENT 'Cost calculated from list unit price and pricing quantity.',
  `ListUnitPrice` DOUBLE COMMENT 'Provider published unit price before discounts.',
  `PricingCategory` STRING COMMENT 'Pricing model used when the charge occurred.',
  `PricingCurrency` STRING COMMENT 'Currency used to price the resource or service.',
  `PricingCurrencyContractedUnitPrice` DOUBLE COMMENT 'Contracted unit price expressed in pricing currency.',
  `PricingCurrencyEffectiveCost` DOUBLE COMMENT 'Effective cost expressed in pricing currency.',
  `PricingCurrencyListUnitPrice` DOUBLE COMMENT 'List unit price expressed in pricing currency.',
  `PricingQuantity` DOUBLE COMMENT 'SKU usage or purchase quantity rated by the pricing unit.',
  `PricingUnit` STRING COMMENT 'Provider unit used for pricing the SKU.',
  `ProviderName` STRING COMMENT 'Entity that made the resource or service available.',
  `PublisherName` STRING COMMENT 'Entity that produced the purchased resource or service.',
  `RegionId` STRING COMMENT 'Provider-assigned region identifier for the resource or service.',
  `RegionName` STRING COMMENT 'Display name of the resource or service region.',
  `ResourceId` STRING COMMENT 'Provider-assigned resource identifier.',
  `ResourceName` STRING COMMENT 'Display name for the resource.',
  `ResourceType` STRING COMMENT 'Kind of resource associated with the charge.',
  `ServiceCategory` STRING COMMENT 'Top-level functional category of the service.',
  `ServiceName` STRING COMMENT 'Service or offering purchased from the provider.',
  `ServiceSubcategory` STRING COMMENT 'Secondary functional category of the service.',
  `SkuId` STRING COMMENT 'Provider-assigned SKU identifier.',
  `SkuMeter` STRING COMMENT 'Metered function or usage measured by the SKU.',
  `SkuPriceDetails` MAP<STRING, STRING> COMMENT 'Common properties associated with the SKU price identifier.',
  `SkuPriceId` STRING COMMENT 'Provider-assigned identifier for the SKU price.',
  `SubAccountId` STRING COMMENT 'Identifier for a resource or service grouping under the billing account.',
  `SubAccountName` STRING COMMENT 'Display name for the sub-account grouping.',
  `SubAccountType` STRING COMMENT 'Provider-assigned type for the sub-account grouping.',
  `Tags` MAP<STRING, STRING> COMMENT 'Provider-defined and user-defined tags evaluated for the charge.',
  `x_Discounts` MAP<STRING, DOUBLE> COMMENT 'AWS-specific discount amounts that apply to the line item.',
  `x_Operation` STRING COMMENT 'AWS operation covered by the line item.',
  `x_ServiceCode` STRING COMMENT 'AWS product or service code measured by the line item.'
) AS
SELECT
  `AvailabilityZone`,
  `BilledCost`,
  `BillingAccountId`,
  `BillingAccountName`,
  `BillingAccountType`,
  `BillingCurrency`,
  `BillingPeriodEnd`,
  `BillingPeriodStart`,
  `CapacityReservationId`,
  `CapacityReservationStatus`,
  `ChargeCategory`,
  `ChargeClass`,
  `ChargeDescription`,
  `ChargeFrequency`,
  `ChargePeriodEnd`,
  `ChargePeriodStart`,
  `CommitmentDiscountCategory`,
  `CommitmentDiscountId`,
  `CommitmentDiscountName`,
  `CommitmentDiscountQuantity`,
  `CommitmentDiscountStatus`,
  `CommitmentDiscountType`,
  `CommitmentDiscountUnit`,
  `ConsumedQuantity`,
  `ConsumedUnit`,
  `ContractedCost`,
  `ContractedUnitPrice`,
  `EffectiveCost`,
  `InvoiceId`,
  `InvoiceIssuerName`,
  `ListCost`,
  `ListUnitPrice`,
  `PricingCategory`,
  `PricingCurrency`,
  `PricingCurrencyContractedUnitPrice`,
  `PricingCurrencyEffectiveCost`,
  `PricingCurrencyListUnitPrice`,
  `PricingQuantity`,
  `PricingUnit`,
  `ProviderName`,
  `PublisherName`,
  `RegionId`,
  `RegionName`,
  `ResourceId`,
  `ResourceName`,
  `ResourceType`,
  `ServiceCategory`,
  `ServiceName`,
  `ServiceSubcategory`,
  `SkuId`,
  `SkuMeter`,
  `SkuPriceDetails`,
  `SkuPriceId`,
  `SubAccountId`,
  `SubAccountName`,
  `SubAccountType`,
  `Tags`,
  `x_Discounts`,
  `x_Operation`,
  `x_ServiceCode`
FROM read_files(
  's3://${s3_bucket}/${s3_prefix}/${export_name}/data/**/*.parquet',
  format => 'parquet'
);

CREATE OR REFRESH MATERIALIZED VIEW `${gold_schema_name}`.`${table_name}_daily`
COMMENT 'AWS FOCUS daily billing rollup managed by FinLake'
AS
SELECT
  CAST(ChargePeriodStart AS DATE) AS x_ChargeDate,
  CAST(DATE_TRUNC('MONTH', BillingPeriodStart) AS DATE) AS x_BillingMonth,
  BillingAccountId,
  BillingAccountName,
  BillingCurrency,
  SubAccountId,
  SubAccountName,
  SubAccountType,
  ProviderName,
  ServiceCategory,
  ServiceSubcategory,
  ServiceName,
  SkuId,
  SkuMeter,
  CAST(SUM(COALESCE(ListCost, 0)) AS DECIMAL(30, 15)) AS ListCost,
  CAST(SUM(COALESCE(BilledCost, 0)) AS DECIMAL(30, 15)) AS BilledCost,
  CAST(SUM(COALESCE(ContractedCost, 0)) AS DECIMAL(30, 15)) AS ContractedCost,
  CAST(SUM(COALESCE(EffectiveCost, 0)) AS DECIMAL(30, 15)) AS EffectiveCost
FROM `${table_name}`
GROUP BY
  CAST(ChargePeriodStart AS DATE),
  CAST(DATE_TRUNC('MONTH', BillingPeriodStart) AS DATE),
  BillingAccountId,
  BillingAccountName,
  BillingCurrency,
  SubAccountId,
  SubAccountName,
  SubAccountType,
  ProviderName,
  ServiceCategory,
  ServiceSubcategory,
  ServiceName,
  SkuId,
  SkuMeter;
