CREATE OR REFRESH MATERIALIZED VIEW ${table_name} (
  `AvailabilityZone` STRING COMMENT 'AWS-assigned availability zone identifier for isolated capacity within a Region.',
  `BilledCost` DOUBLE COMMENT 'Charge used for invoicing after reduced rates and discounts, excluding upfront amortization.',
  `BillingAccountId` STRING COMMENT 'AWS-assigned identifier for the billing account.',
  `BillingAccountName` STRING COMMENT 'Display name assigned to the billing account.',
  `BillingAccountType` STRING COMMENT 'AWS-assigned billing account type.',
  `BillingCurrency` STRING COMMENT 'Currency code used to bill the charge.',
  `BillingPeriodEnd` TIMESTAMP COMMENT 'Exclusive end timestamp of the billing period.',
  `BillingPeriodStart` TIMESTAMP COMMENT 'Inclusive start timestamp of the billing period.',
  `CapacityReservationId` STRING COMMENT 'AWS-assigned identifier for the capacity reservation.',
  `CapacityReservationStatus` STRING COMMENT 'Whether the charge consumed capacity reservation commitment or represents unused capacity.',
  `ChargeCategory` STRING COMMENT 'Highest-level classification of the charge by billing nature.',
  `ChargeClass` STRING COMMENT 'Whether the row corrects a previously invoiced billing period.',
  `ChargeDescription` STRING COMMENT 'Self-contained summary of the charge purpose and price.',
  `ChargeFrequency` STRING COMMENT 'How often the charge occurs.',
  `ChargePeriodEnd` TIMESTAMP COMMENT 'Exclusive end timestamp of the charge period.',
  `ChargePeriodStart` TIMESTAMP COMMENT 'Inclusive start timestamp of the charge period.',
  `CommitmentDiscountCategory` STRING COMMENT 'Whether the commitment discount is based on usage quantity or spend.',
  `CommitmentDiscountId` STRING COMMENT 'AWS-assigned identifier for the commitment discount.',
  `CommitmentDiscountName` STRING COMMENT 'Display name assigned to the commitment discount.',
  `CommitmentDiscountQuantity` DOUBLE COMMENT 'Purchased or accounted commitment discount amount in commitment discount units.',
  `CommitmentDiscountStatus` STRING COMMENT 'Whether the charge corresponds to consumed or unused commitment.',
  `CommitmentDiscountType` STRING COMMENT 'AWS-assigned type of commitment discount applied to the row.',
  `CommitmentDiscountUnit` STRING COMMENT 'AWS measurement unit for the commitment discount quantity.',
  `ConsumedQuantity` DOUBLE COMMENT 'Metered SKU usage volume based on ConsumedUnit.',
  `ConsumedUnit` STRING COMMENT 'AWS measurement unit for consumed metered usage.',
  `ContractedCost` DOUBLE COMMENT 'Cost calculated from contracted unit price and PricingQuantity.',
  `ContractedUnitPrice` DOUBLE COMMENT 'Agreed unit price for one PricingUnit before commitment or other discounts.',
  `EffectiveCost` DOUBLE COMMENT 'Amortized charge after reduced rates, discounts, and applicable prepaid purchases.',
  `InvoiceId` STRING COMMENT 'AWS-assigned invoice identifier for charges in the billing period.',
  `InvoiceIssuerName` STRING COMMENT 'Entity responsible for invoicing the consumed resources or services.',
  `ListCost` DOUBLE COMMENT 'Cost calculated from ListUnitPrice and PricingQuantity.',
  `ListUnitPrice` DOUBLE COMMENT 'Provider-published unit price for one PricingUnit before discounts.',
  `PricingCategory` STRING COMMENT 'Pricing model used for the charge at the time of use or purchase.',
  `PricingCurrency` STRING COMMENT 'Currency denomination used to price the resource or service.',
  `PricingCurrencyContractedUnitPrice` DOUBLE COMMENT 'Contracted unit price expressed in PricingCurrency.',
  `PricingCurrencyEffectiveCost` DOUBLE COMMENT 'Effective cost expressed in PricingCurrency.',
  `PricingCurrencyListUnitPrice` DOUBLE COMMENT 'List unit price expressed in PricingCurrency.',
  `PricingQuantity` DOUBLE COMMENT 'SKU quantity used or purchased based on PricingUnit.',
  `PricingUnit` STRING COMMENT 'AWS measurement unit used to rate usage or purchase quantities.',
  `ProviderName` STRING COMMENT 'Entity that made the resources or services available for purchase.',
  `PublisherName` STRING COMMENT 'Entity that produced the purchased resources or services.',
  `RegionId` STRING COMMENT 'AWS-assigned identifier for the geographic area where the resource or service was provided.',
  `RegionName` STRING COMMENT 'Display name for the geographic area where the resource or service was provided.',
  `ResourceId` STRING COMMENT 'AWS-assigned identifier for the resource.',
  `ResourceName` STRING COMMENT 'Display name assigned to the resource.',
  `ResourceType` STRING COMMENT 'Kind of resource the charge applies to.',
  `ServiceCategory` STRING COMMENT 'Highest-level service classification by core function.',
  `ServiceName` STRING COMMENT 'Purchased provider offering, such as a cloud service or SaaS product.',
  `ServiceSubcategory` STRING COMMENT 'Secondary service classification by core function.',
  `SkuId` STRING COMMENT 'AWS-specified unique identifier for the SKU.',
  `SkuMeter` STRING COMMENT 'Functionality metered or measured by the SKU for the charge.',
  `SkuPriceDetails` MAP<STRING, STRING> COMMENT 'Properties of a SKU price identifier shared by instances of that SKU price.',
  `SkuPriceId` STRING COMMENT 'AWS-specified unique identifier for the SKU price.',
  `SubAccountId` STRING COMMENT 'Identifier for a grouping of resources or services used for access or cost management.',
  `SubAccountName` STRING COMMENT 'Name assigned to a grouping of resources or services used for access or cost management.',
  `SubAccountType` STRING COMMENT 'AWS-assigned type for the sub-account grouping.',
  `Tags` MAP<STRING, STRING> COMMENT 'Provider-defined and user-defined tags evaluated for the charge.',
  `x_Discounts` MAP<STRING, DOUBLE> COMMENT 'AWS extension containing discount key-value pairs that apply to the line item.',
  `x_Operation` STRING COMMENT 'AWS extension containing the specific operation covered by the line item.',
  `x_ServiceCode` STRING COMMENT 'AWS extension containing the measured product code.'
) AS
SELECT
  `AvailabilityZone`,
  `BilledCost`,
  `BillingAccountId`,
  `BillingAccountName`,
  `BillingAccountType`,
  `BillingCurrency`,
  `BillingPeriodEnd`,
  `BillingPeriodStart`,
  `CapacityReservationId`,
  `CapacityReservationStatus`,
  `ChargeCategory`,
  `ChargeClass`,
  `ChargeDescription`,
  `ChargeFrequency`,
  `ChargePeriodEnd`,
  `ChargePeriodStart`,
  `CommitmentDiscountCategory`,
  `CommitmentDiscountId`,
  `CommitmentDiscountName`,
  `CommitmentDiscountQuantity`,
  `CommitmentDiscountStatus`,
  `CommitmentDiscountType`,
  `CommitmentDiscountUnit`,
  `ConsumedQuantity`,
  `ConsumedUnit`,
  `ContractedCost`,
  `ContractedUnitPrice`,
  `EffectiveCost`,
  `InvoiceId`,
  `InvoiceIssuerName`,
  `ListCost`,
  `ListUnitPrice`,
  `PricingCategory`,
  `PricingCurrency`,
  `PricingCurrencyContractedUnitPrice`,
  `PricingCurrencyEffectiveCost`,
  `PricingCurrencyListUnitPrice`,
  `PricingQuantity`,
  `PricingUnit`,
  `ProviderName`,
  `PublisherName`,
  `RegionId`,
  `RegionName`,
  `ResourceId`,
  `ResourceName`,
  `ResourceType`,
  `ServiceCategory`,
  `ServiceName`,
  `ServiceSubcategory`,
  `SkuId`,
  `SkuMeter`,
  `SkuPriceDetails`,
  `SkuPriceId`,
  `SubAccountId`,
  `SubAccountName`,
  `SubAccountType`,
  `Tags`,
  `x_Discounts`,
  `x_Operation`,
  `x_ServiceCode`
FROM read_files(
  's3://${s3_bucket}/${s3_prefix}/${export_name}/data/**/*.parquet',
  format => 'parquet'
);

CREATE OR REFRESH MATERIALIZED VIEW `${gold_schema_name}`.`${table_name}_daily`
COMMENT 'AWS FOCUS daily billing rollup managed by FinLake'
AS
SELECT
  CAST(ChargePeriodStart AS DATE) AS x_ChargeDate,
  CAST(DATE_TRUNC('MONTH', BillingPeriodStart) AS DATE) AS x_BillingMonth,
  BillingAccountId,
  BillingAccountName,
  BillingCurrency,
  SubAccountId,
  SubAccountName,
  SubAccountType,
  ProviderName,
  ServiceCategory,
  ServiceSubcategory,
  ServiceName,
  SkuId,
  SkuMeter,
  CAST(SUM(COALESCE(ListCost, 0)) AS DECIMAL(30, 15)) AS ListCost,
  CAST(SUM(COALESCE(BilledCost, 0)) AS DECIMAL(30, 15)) AS BilledCost,
  CAST(SUM(COALESCE(ContractedCost, 0)) AS DECIMAL(30, 15)) AS ContractedCost,
  CAST(SUM(COALESCE(EffectiveCost, 0)) AS DECIMAL(30, 15)) AS EffectiveCost
FROM `${table_name}`
GROUP BY
  CAST(ChargePeriodStart AS DATE),
  CAST(DATE_TRUNC('MONTH', BillingPeriodStart) AS DATE),
  BillingAccountId,
  BillingAccountName,
  BillingCurrency,
  SubAccountId,
  SubAccountName,
  SubAccountType,
  ProviderName,
  ServiceCategory,
  ServiceSubcategory,
  ServiceName,
  SkuId,
  SkuMeter;
